### ISSUE TITLE
cursor issues on ie with date separator

### ISSUE THREAD

**Issue by checkin247** [Mottie/Keyboard#611] opened 2017-10-17 09:35 UTC
Issue is related to IE, 
Tested on IE and Chrome

I am using some logic to automatically add a separator on keyboard input for [date separator](https://jsfiddle.net/ChrisCoray/hLkjhsce/).

Using the real keyboard there is no issue.
With mottie keyboard, the cursor moves back one position before the separator.
I also tried to add the separator with the typing extension....
I also tried kb.caret('end')

The only solution (after trying a lot) was using a [jQuery plugin](https://css-tricks.com/snippets/jquery/move-cursor-to-end-of-textarea-or-input/) to move cursor to the end.

I implemented it with
```
$("input").on('focus', function(e){
	$(this).putCursorAtEnd();
});

```
Maybe this helps someone or there is a built in function to overcome this issue

**Comment by Mottie** [comment] 2017-10-17 12:46
Hi @checkin247!

There is a built-in function to [move the caret](https://github.com/Mottie/Keyboard/wiki/Methods#caret). It is as you mentioned `kb.caret('end')`. I think it isn't working because you need to update the last position &ndash; I'll update the internal function to do this automatically.

The problem is that this keyboard plugin isn't 100% compatible with masking plugins. They both will fight for caret control (see #201). Also mentioned in that issue is the problem with using mask plugins with screen readers and a possible solution.

**Comment by checkin247** [comment] 2017-10-20 14:40
@Mottie , thanks for taking the time to explain that to me.
I will try this out and comment

**Comment by Mottie** [comment] 2018-04-19 13:03
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Closed by Mottie** 2018-04-19 13:03 UTC
