### ISSUE TITLE
Public CDN support

### ISSUE THREAD

**Issue by tobias-kuendig** [Mottie/Keyboard#434] opened 2016-02-17 10:02 UTC
It would be great to be able to include the keyboard from a public cdn like cdnjs.com

See https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#d-adding-a-new-library

Is there any support planned?

**Comment by Mottie** [comment] 2016-02-17 13:54
Hi @tobias-kuendig!

Well, I started trying to add this repo to cdnjs... 

* The npm auto update code was added to the package.json ([ref](https://github.com/Mottie/Keyboard/commit/b6a7969080c71d2972c235e1f722e87882f9e8d5#diff-5)).
* I forgot how unwieldy it was to deal with the size of cdnjs, but I discovered use of a sparse checkout and shallow clone.
* Then I discovered the documentation was missing the "filename" requirement for autoupdate because I couldn't get my tests to pass.
* So I opened a PR: https://github.com/cdnjs/cdnjs/pull/6765, and started waiting for that to get merged before adding this repo because it would be added to that PR since cdnjs doesn't appear to use branches.
* Then I forgot about it :grin: 

So, maybe it would be easier to request they add it.

**Comment by Mottie** [comment] 2016-02-17 21:29
Actually, the issue is that I couldn't get `npm test` to pass...

see https://github.com/cdnjs/cdnjs/issues/4961#issuecomment-173079996

**Comment by Mottie** [comment] 2016-02-17 23:11
Ok... see https://github.com/cdnjs/cdnjs/pull/7010!

**Comment by Mottie** [comment] 2016-02-18 14:06
Done! https://cdnjs.com/libraries/virtual-keyboard

Thanks again!

**Closed by Mottie** 2016-02-18 14:06 UTC
Labels: ♥️ Assistance Welcome

**Comment by tobias-kuendig** [comment] 2016-02-18 14:16
Awesome, thank you!
