### ISSUE TITLE
Uncaught TypeError : Cannot read property 'reveal' of undefined

### ISSUE THREAD

**Issue by bmontassier** [Mottie/Keyboard#674] opened 2018-06-12 14:12 UTC
Hello, I hava this error in my console on this code : 
`<script type="text/javascript">
				$('input.navsearch').click(function(){
					alert('Test');
  				$('#search').getkeyboard().reveal();
				});
				</script>`

Thanks.

**Comment by Mottie** [comment] 2018-06-12 14:22
Hi @bmontassier!

Please make sure that the keyboard is initialized on the input before using the `reveal` function. Try this:

```js
$('input.navsearch').click(function(){
  $('#search').keyboard({
    initialized: function(e, keyboard) {
      keyboard.reveal();
    }
  });
});
```

**Comment by bmontassier** [comment] 2018-06-12 14:28
Working but look at this keyboard

![image](https://user-images.githubusercontent.com/35603054/41296646-afacbc04-6e5d-11e8-9c01-62b490cd1ddc.png)

**Comment by Mottie** [comment] 2018-06-12 14:58
That looks like either jQuery UI position utility isn't being loaded, or there is some other css interfering with jQuery UI's css. It would be helpful if the issue could be reproduced in a [demo like this one](http://jsfiddle.net/Mottie/egb3a1sk/).

**Comment by Mottie** [comment] 2018-07-05 12:19
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Closed by Mottie** 2018-07-05 12:19 UTC
Labels: How to...
