### ISSUE TITLE
close keyboard is it open after certain time

### ISSUE THREAD

**Issue by almih2m** [Mottie/Keyboard#612] opened 2017-10-22 09:19 UTC
I try to close the keyboard if the user does not close the screen in a certain time
is there any way to close it? by using code

also when I load screen on the old screen and the keyboard is open. the keyboard stay open on loaded screen .is there any way to solve that problem?

Thank you

**Comment by Mottie** [comment] 2017-10-22 13:58
Hi @almih2m!

You can use a combination of [Events and methods](https://github.com/Mottie/Keyboard/wiki/Methods) to close the keyboard if there is no activity after a certain amount of time.

In [this example](http://jsfiddle.net/Mottie/egb3a1sk/3171/), the timer is set to 3 seconds

```js
$(function() {
  var closeTimer,
    timeUntilClose = 3000; // 3 seconds

  function updateTimer(e, kb) {
    clearTimeout(closeTimer);
    closeTimer = setTimeout(function() {
      kb.close(kb.options.autoAccept);
    }, timeUntilClose);
  }

  $('#keyboard').keyboard({
      // keep any changes
      autoAccept: true,
      visible: updateTimer,
      change: updateTimer,
      beforeClose: updateTimer
    });
});
```

> also when I load screen on the old screen and the keyboard is open. the keyboard stay open on loaded screen

I'm not really sure what you mean by that... is the keyboard set to be `alwaysOpen`? Then the above code won't work.

**Comment by almih2m** [comment] 2017-10-23 05:38
I make timer to load page if user does not click on anything on screen

but when new page load over the old page and the keyboard was open, the keyboard not hide and freezes the screen

**Comment by almih2m** [comment] 2017-10-23 05:53
@Mottie 
your code work but if the input does not validate, the keyboard not close 
 I do not need to save input, is there any to close the keyboard without saving the input?

Thank you a lot

**Comment by almih2m** [comment] 2017-10-23 07:19
Another thing, I have visible as a function
how I can call updateTimer function?
visible: function () {
          ..........
          ........
         .........

        },

Thank you a lot for your help

**Comment by Mottie** [comment] 2017-10-23 12:31
> but when new page load over the old page and the keyboard was open, the keyboard not hide and freezes the screen

I'm still not sure what you mean. Please share the code for the timer you're using. The css to increase the z-index is not the cause of this problem.

> how I can call updateTimer function?

Follow this example:

```js
$("#keyboard").keyboard({
  // keep any changes
  autoAccept: true,
  visible: function(e, kb) {
    // ...
    updateTimer(e, kb);
  },
  change: updateTimer,
  beforeClose: updateTimer
});
```

**Comment by Mottie** [comment] 2017-11-23 02:09
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Closed by Mottie** 2017-11-23 02:09 UTC
Labels: Demo, How to...
