### ISSUE TITLE
Keyboard accept time hidden.bs.modal event run 

### ISSUE THREAD

**Issue by muradsofiyev** [Mottie/Keyboard#566] opened 2017-06-02 13:14 UTC
When I'm accepted keyboard resets all input

**Comment by Mottie** [comment] 2017-06-02 14:48
Hi @muradsofiyev!

Would you please [modify this demo](http://jsfiddle.net/Mottie/egb3a1sk/) to show the problem being described?

**Comment by muradsofiyev** [comment] 2017-06-03 06:51
Hey i find problem  http://jsfiddle.net/u5kuwxuk/ watch this example  your plugin  call my modal hidden event

**Comment by Mottie** [comment] 2017-06-03 12:15
I still don't understand the issue. Please describe the problem, and what steps are needed to perform to reproduce it.

**Comment by ketterus** [comment] 2017-06-03 13:08
You need to give your <button> a different "id" or "class". Your using the
same in your toggle function for both.

**Comment by muradsofiyev** [comment] 2017-06-03 19:18
When i accepted keyboard keyboard close but my modal close event listener (hidden.bs.modal) run You see that open your console http://jsfiddle.net/u5kuwxuk/ this example and accept keyboard

**Comment by Mottie** [comment] 2017-06-08 18:20
Ok, I understand now... sorry it took me so long to respond.

The problem is that the keyboard triggers a `hidden` event when it hides, and Bootstrap triggers a `hidden.bs.modal` to show that the modal was hidden.

You can solve this issue in two ways:

1. Change the keyboard event that is triggered when it is hidden ([docs](https://github.com/Mottie/Keyboard/wiki/Methods#event-names)):

      ```js
      $.keyboard.events.kbHidden = "keyboardHidden";
      ```
2. Because jQuery uses namespacing, any characters after the first period in the event will be added as a namespace. Therefore, check the namespace of the event before executing any code ([demo](http://jsfiddle.net/Mottie/u5kuwxuk/2/)):

    ```js
    $("#myModal").on('hidden.bs.modal', function(event) {
      if (event.namespace === 'bs.modal') {
        console.log('hello world');
      }
    });
    ```

**Comment by Mottie** [comment] 2017-07-27 16:26
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Closed by Mottie** 2017-07-27 16:26 UTC
Labels: Demo, How to...
