### ISSUE TITLE
I want to Insert Dot in Input type number with step=any without changing input type. What is the solution?

### ISSUE THREAD

**Issue by tauseefjanjua** [Mottie/Keyboard#717] opened 2019-01-02 06:23 UTC
I've seen examples, in those examples input type text is selected, but the issue is text is also typed in via tangible keyboard. I tried input type=number and the tangible keyboard inserts dot and input accepts it but when I type dot via Mottie/keyboard (virtual keyboard) input type=number doesn't accept dot and returns warning in console:

(The specified value "." is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?)

**Comment by Mottie** [comment] 2019-01-02 13:34
Hi @tauseefjanjua!

I'm not sure what issue you're running into, but obtaining the caret position is necessary for a nice user experience. And since only text, search, url, telephone and password type input allow checking the caret position ([ref](https://html.spec.whatwg.org/multipage/input.html#do-not-apply)), the preview input type number is automatically switched to a text type input.

I've never seen the error reported caused by this virtual keyboard. Does the input include a pattern attribute? Would you share the html & code being used?

If you want to prevent alphabetic text from being entered from the physical keyboard, change the layout to "num" and set the [`restrictInput` option](https://github.com/Mottie/Keyboard/wiki/Usability#restrictinput) to `true`.

**Comment by Mottie** [comment] 2019-02-20 04:28
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Closed by Mottie** 2019-02-20 04:28 UTC
